package koneksidbversipbolegal;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import static javafx.scene.input.KeyCode.X;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class DataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form DataSiswa
     */
    
    Connection koneksi;
    
    public DataSiswa() throws SQLException, ParseException {
        initComponents();
        koneksi = SQLiteConnection.connect();
        showData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterJK = new javax.swing.ButtonGroup();
        filterUsia = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmdHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdTambah = new javax.swing.JButton();
        cmdRefresh = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_siswa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox<>();
        cmbKelas = new javax.swing.JComboBox<>();
        asc = new javax.swing.JRadioButton();
        cewe = new javax.swing.JRadioButton();
        cowo = new javax.swing.JRadioButton();
        desc = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jksemua = new javax.swing.JRadioButton();
        agenone = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JLabel();
        cmdHapus1 = new javax.swing.JButton();
        cmdHapus2 = new javax.swing.JButton();
        cmdHapus3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        cmdHapus.setBackground(new java.awt.Color(204, 255, 204));
        cmdHapus.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel1.setText("Data Siswa");

        cmdTambah.setBackground(new java.awt.Color(204, 255, 204));
        cmdTambah.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdRefresh.setBackground(new java.awt.Color(204, 255, 204));
        cmdRefresh.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdRefresh.setText("Refresh");
        cmdRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefreshActionPerformed(evt);
            }
        });

        cmdEdit.setBackground(new java.awt.Color(204, 255, 204));
        cmdEdit.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdEdit.setText("Ubah");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        tbl_siswa.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        tbl_siswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_siswa.getTableHeader().setReorderingAllowed(false);
        tbl_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_siswa);
        if (tbl_siswa.getColumnModel().getColumnCount() > 0) {
            tbl_siswa.getColumnModel().getColumn(0).setMinWidth(20);
            tbl_siswa.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_siswa.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Kelas");

        jLabel4.setText("Jurusan");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Usia");

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        cmbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJurusanActionPerformed(evt);
            }
        });

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        cmbKelas.setToolTipText("");

        filterUsia.add(asc);
        asc.setText("ASC");

        filterJK.add(cewe);
        cewe.setText("P");

        filterJK.add(cowo);
        cowo.setText("L");
        cowo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cowoActionPerformed(evt);
            }
        });

        filterUsia.add(desc);
        desc.setText("DESC");

        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filterJK.add(jksemua);
        jksemua.setText("Semua");
        jksemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jksemuaActionPerformed(evt);
            }
        });

        filterUsia.add(agenone);
        agenone.setText("None");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jksemua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agenone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asc)
                            .addComponent(cowo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cewe)
                            .addComponent(desc))
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cowo)
                            .addComponent(cewe)
                            .addComponent(jksemua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asc)
                            .addComponent(jLabel6)
                            .addComponent(desc)
                            .addComponent(jButton1)
                            .addComponent(agenone))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        searchTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTF.setText("SEARCH...");
        searchTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTFMouseClicked(evt);
            }
        });
        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        jButton2.setText("CARI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        jLabel2.setText("Filter");

        jLabel7.setText("Total Siswa");

        cmdHapus1.setBackground(new java.awt.Color(204, 255, 204));
        cmdHapus1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdHapus1.setText("KELAS");
        cmdHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus1ActionPerformed(evt);
            }
        });

        cmdHapus2.setBackground(new java.awt.Color(204, 255, 204));
        cmdHapus2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdHapus2.setText("JURUSAN");
        cmdHapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus2ActionPerformed(evt);
            }
        });

        cmdHapus3.setBackground(new java.awt.Color(204, 255, 204));
        cmdHapus3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        cmdHapus3.setText("ABOUT");
        cmdHapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(351, 351, 351))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdHapus)
                .addGap(123, 123, 123)
                .addComponent(cmdHapus1)
                .addGap(18, 18, 18)
                .addComponent(cmdHapus2)
                .addGap(18, 18, 18)
                .addComponent(cmdHapus3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(890, Short.MAX_VALUE)
                    .addComponent(cmdRefresh)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdEdit)
                    .addComponent(cmdHapus)
                    .addComponent(cmdHapus1)
                    .addComponent(cmdHapus2)
                    .addComponent(cmdHapus3))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(342, Short.MAX_VALUE)
                    .addComponent(cmdRefresh)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefreshActionPerformed
        try {
            showData();
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdRefreshActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        // TODO add your handling code here:
        String nisDelete = tbl_siswa.getValueAt(baris, 1).toString();
        try{
            Statement stm = koneksi.createStatement();
            String query = "DELETE FROM t_siswa WHERE nis = '" + nisDelete+"';";
            System.out.println(nisDelete);
            
            int berhasil = stm.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
                dtm.getDataVector().removeAllElements();
                showData();
            }else{
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
                
            }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        try {
            this.setVisible(false);
            ManageData tambahData = new ManageData(this,true, "Tambah","");
            tambahData.setVisible(true);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdTambahActionPerformed

    int baris;
    private void tbl_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_siswaMouseClicked
        // TODO add your handling code here:
        baris = tbl_siswa.getSelectedRow();
    }//GEN-LAST:event_tbl_siswaMouseClicked

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            String nis = tbl_siswa.getValueAt(baris, 1).toString();
            System.out.println(nis);
            ManageData tambahData = new ManageData(this,true, "Edit",nis);
            tambahData.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJurusanActionPerformed

    private void cowoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cowoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cowoActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        searchTF.setText("");
    }//GEN-LAST:event_searchTFActionPerformed

    private void searchTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTFMouseClicked
        // TODO add your handling code here:
        searchTF.setText("");
    }//GEN-LAST:event_searchTFMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            filterSearch();
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            filterData();
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jksemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jksemuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jksemuaActionPerformed

    private void cmdHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus1ActionPerformed
        try {
            new DataKelas().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_cmdHapus1ActionPerformed

    private void cmdHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus2ActionPerformed
        new DataJurusan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdHapus2ActionPerformed

    private void cmdHapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus3ActionPerformed
        new About().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdHapus3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataSiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    String filename = "D:\\KELAS SEBELAS\\PBO\\Praktikum_PBO\\NETBEANS\\KoneksiDBversiPBOLEGAL\\dist\\data\\Settings.a";
    
    public void read() {
        BufferedReader br = null;
        FileReader fr = null;

        try {
            //br = new BufferedReader(new FileReader(FILENAME));
            fr = new FileReader(filename);
            br = new BufferedReader(fr);

            String sCurrentLine;

            while ((sCurrentLine = br.readLine()) != null) {
                
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
                if (fr != null) {
                    fr.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    DefaultTableModel dtm;
    String query = "SELECT * FROM ((t_siswa INNER JOIN t_kelas ON t_siswa.id_kelas = t_kelas.id_kelas) INNER JOIN t_jurusan ON t_siswa.id_jurusan = t_jurusan.id_jurusan)";
    
    public void filterData() throws SQLException, ParseException{
        String[] kolom = {"NO" , "NIS" , "Nama" , "Kelas" , "Jurusan" , "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Usia"};
        dtm = new DefaultTableModel(null, kolom);
        
        String filterkelas = cmbKelas.getSelectedItem().toString();
        String filterjurusan = cmbJurusan.getSelectedItem().toString();
        String jk = "";
        String urut = "";
        //Kelas
        if (filterkelas.equalsIgnoreCase("semua")) {
            filterkelas="";
        }
        //Jurusan
        if (filterjurusan.equalsIgnoreCase("semua")) {
            filterjurusan="";
        }
        //Tingkat
        
        //Jenkel
        if (cowo.isSelected()) {
            jk = "L";
        }else if (cewe.isSelected()) {
                jk = "P";
        }else if (jksemua.isSelected()) {
                jk = "";
            }
        //URUT
        if (asc.isSelected()) {
            urut = "ORDER BY tgl_lahir ASC";
        }else if (desc.isSelected()) {
            urut = "ORDER BY tgl_lahir DESC";
        }else if (agenone.isSelected()) {
            urut = "";
        }
        String query1 = query + " WHERE t_kelas.nama_kelas LIKE '%"+filterkelas+"%' AND t_jurusan.nama_jurusan LIKE '%"+filterjurusan+"%' AND t_siswa.jenkel LIKE '%"+jk+"%' " + urut;
        System.out.println(query1);
        int totalSiswa=0;
        Statement stm = koneksi.createStatement();
        ResultSet rs = stm.executeQuery(query1);
            
        try{
            
            int no= 1;
            while(rs.next()){
                totalSiswa++;
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String namaKelas = rs.getString("nama_kelas");
                int tingkatKelas = rs.getInt("tingkat");
                String tingkat = "";
                if (tingkatKelas == 1) {
                    tingkat = "X";
                }
                else if (tingkatKelas == 2) {
                    tingkat = "XI";
                }
                else if (tingkatKelas == 3) {
                    tingkat = "XII";
                }
                else{
                    tingkat = "XIII";
                }
                String jurusan = rs.getString("nama_jurusan");
                String jenkel = rs.getString("jenkel");
                SimpleDateFormat input = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat output = new SimpleDateFormat("dd/MM/yyyy");
                String tgl_lahir = rs.getString("tgl_lahir");
                Date parsed = input.parse(tgl_lahir);
                String tl = output.format(parsed);
                String alamat = rs.getString("alamat");
                
                //usia
                Calendar cal = Calendar.getInstance();
                Date now = cal.getTime();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                int tahun_lahir = Integer.parseInt(sdf.format(parsed));
                int tahun_now = Integer.parseInt(sdf.format(now));
                int usiaint = (tahun_now-tahun_lahir)/10000;
                String usia = "" + usiaint;
                
             
                dtm.addRow(new String[]{no+"",nis,nama,tingkat+"-"+namaKelas,jurusan,jenkel,tgl_lahir+"",alamat,usia+""});
                no++;
            }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        finally{
            rs.close();
        }
        tbl_siswa.setModel(dtm);
        fieldTotal.setText(""+totalSiswa);
        query1 ="";
            
        
         
    }
    
    public void filterSearch() throws SQLException, ParseException{
        String[] kolom = {"NO" , "NIS" , "Nama" , "Kelas" , "Jurusan" , "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Usia"};
        dtm = new DefaultTableModel(null, kolom);
        String search = searchTF.getText();
        String query1 = query + " WHERE nama LIKE '%" + search + "%'";
        Statement stm = koneksi.createStatement();
        ResultSet rs = stm.executeQuery(query1);
            
        int totalSiswa = 0;
        try{
            System.out.println(query1);
            int no = 1;
            while(rs.next()){
                totalSiswa++;
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String namaKelas = rs.getString("nama_kelas");
                int tingkatKelas = rs.getInt("tingkat");
                String tingkat = "";
                if (tingkatKelas == 1) {
                    tingkat = "X";
                }
                else if (tingkatKelas == 2) {
                    tingkat = "XI";
                }
                else if (tingkatKelas == 3) {
                    tingkat = "XII";
                }
                else{
                    tingkat = "XIII";
                }
                String jurusan = rs.getString("nama_jurusan");
                String jenkel = rs.getString("jenkel");
                SimpleDateFormat input = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat output = new SimpleDateFormat("dd/MM/yyyy");
                String tgl_lahir = rs.getString("tgl_lahir");
                Date parsed = input.parse(tgl_lahir);
                String tl = output.format(parsed);
                String alamat = rs.getString("alamat");
                
                //usia
                Calendar cal = Calendar.getInstance();
                Date now = cal.getTime();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                int tahun_lahir = Integer.parseInt(sdf.format(parsed));
                int tahun_now = Integer.parseInt(sdf.format(now));
                int usiaint = (tahun_now-tahun_lahir)/10000;
                String usia = "" + usiaint;
                
             
                dtm.addRow(new String[]{no+"",nis,nama,tingkat+"-"+namaKelas,jurusan,jenkel,tgl_lahir+"",alamat,usia+""});
                no++;
                
                //jang kelas
                String que2 = "SELECT * FROM t_kelas GROUP BY id_kelas";
                ResultSet rs2 = stm.executeQuery(que2);
                while(rs2.next()){
                    String id_kelas = rs2.getString("nama_kelas");
                    cmbKelas.addItem(id_kelas);
                }
                
                //jang jurusan
                String que3 = "SELECT * FROM t_jurusan GROUP BY id_jurusan";
                ResultSet rs3 = stm.executeQuery(que3);
                while(rs3.next()){
                    String id_jurusan = rs3.getString("nama_jurusan");
                    cmbJurusan.addItem(id_jurusan);

            }
        }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        finally{
            rs.close();
        }
        
        tbl_siswa.setModel(dtm);
        fieldTotal.setText(totalSiswa+"");
        query1 = "";
    }
                
    
        
    
    
    public void showDatafail() throws SQLException, ParseException{
        String[] kolom = {"NO" , "NIS" , "Nama" , "Kelas" , "Jurusan" , "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Usia"};
        String i=7+"";
        dtm = new DefaultTableModel(null, kolom);
        query = query + "";
        System.out.println(query);
        
        int totalSiswa=0;
        try{
            
            Statement stm = koneksi.createStatement();
            ResultSet rs = stm.executeQuery(query);
            int no= 1;
            while(rs.next()){
                totalSiswa++;
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String namaKelas = rs.getString("nama_kelas");
                int tingkatKelas = rs.getInt("tingkat");
                String tingkat = "";
                if (tingkatKelas == 1) {
                    tingkat = "X";
                }
                else if (tingkatKelas == 2) {
                    tingkat = "XI";
                }
                else if (tingkatKelas == 3) {
                    tingkat = "XII";
                }
                else{
                    tingkat = "XIII";
                }
                String jurusan = rs.getString("nama_jurusan");
                String jenkel = rs.getString("jenkel");
                SimpleDateFormat input = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat output = new SimpleDateFormat("dd/MM/yyyy");
                String tgl_lahir = rs.getString("tgl_lahir");
                Date parsed = input.parse(tgl_lahir);
                String tl = output.format(parsed);
                String alamat = rs.getString("alamat");
                
                //usia
                Calendar cal = Calendar.getInstance();
                Date now = cal.getTime();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                int tahun_lahir = Integer.parseInt(sdf.format(parsed));
                int tahun_now = Integer.parseInt(sdf.format(now));
                int usiaint = (tahun_now-tahun_lahir)/10000;
                String usia = "" + usiaint;
                
             
                dtm.addRow(new String[]{no+"",nis,nama,tingkat+"-"+namaKelas,jurusan,jenkel,tgl_lahir+"",alamat,usia+""});
                no++;
            }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        tbl_siswa.setModel(dtm);
        fieldTotal.setText(""+totalSiswa);
        
    }
    public void showData() throws SQLException, ParseException{
        String[] kolom = {"NO" , "NIS" , "Nama" , "Kelas" , "Jurusan" , "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Usia"};
        dtm = new DefaultTableModel(null, kolom);
        int totalSiswa = 0;
        try{
            Statement stm = koneksi.createStatement();
            ResultSet rs = stm.executeQuery(query);
            int no = 1;
            while(rs.next()){
                totalSiswa++;
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String nama_kelas = rs.getString("nama_kelas");
                int tingkat_kelas = rs.getInt("tingkat");
                String tingkat = "";
                if (tingkat_kelas == 1) {
                    tingkat = tingkat + "X";
                }
                else if (tingkat_kelas == 2) {
                    tingkat = tingkat + "XI";
                }
                else if (tingkat_kelas == 3) {
                    tingkat = tingkat + "XII";
                }
                else if (tingkat_kelas == 4) {
                    tingkat = tingkat + "XIII";
                }
                String jurusan = rs.getString("nama_jurusan");
                String jenkel = rs.getString("jenkel");
                SimpleDateFormat input = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat output = new SimpleDateFormat("dd/MM/yyyy");
                String tgl_lahir = rs.getString("tgl_lahir");
                Date parsed = input.parse(tgl_lahir);
                String tl = output.format(parsed);
                String alamat = rs.getString("alamat");
                
                //usia
                Calendar cal = Calendar.getInstance();
                Date now = cal.getTime();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                int tahun_lahir = Integer.parseInt(sdf.format(parsed));
                int tahun_now = Integer.parseInt(sdf.format(now));
                int usiaint = (tahun_now-tahun_lahir)/10000;
                String usia = "" + usiaint;
                
                dtm.addRow(new String[]{no+"",nis,nama,tingkat+"-"+nama_kelas,jurusan,jenkel,tgl_lahir+"",alamat,usia+""});
                no++;
            }
                String que2 = "SELECT * FROM t_kelas GROUP BY id_kelas";
                ResultSet rs2 = stm.executeQuery(que2);
                while(rs2.next()){
                    String id_kelas = rs2.getString("nama_kelas");
                    cmbKelas.addItem(id_kelas);
                }
                
                String que3 = "SELECT * FROM t_jurusan GROUP BY id_jurusan";
                ResultSet rs3 = stm.executeQuery(que3);
                while(rs3.next()){
                    String id_jurusan = rs3.getString("nama_jurusan");
                    cmbJurusan.addItem(id_jurusan);
                }
            
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        tbl_siswa.setModel(dtm);
        fieldTotal.setText(""+totalSiswa);
    }
    public void showDatafailtoo(){
        String[] kolom = {"NO" , "NIS" , "Nama" , "Kelas" , "Jurusan" , "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Usia"};
        
        dtm = new DefaultTableModel(null, kolom);
        
        int totalSiswa=0;
        try{
            
            Statement stm = koneksi.createStatement();
            ResultSet rs = stm.executeQuery(query);
            int no= 1;
            while(rs.next()){
                totalSiswa++;
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String namaKelas = rs.getString("nama_kelas");
                int tingkatKelas = rs.getInt("tingkat");
                String tingkat = "";
                if (tingkatKelas == 1) {
                    tingkat = "X";
                }
                else if (tingkatKelas == 2) {
                    tingkat = "XI";
                }
                else if (tingkatKelas == 3) {
                    tingkat = "XII";
                }
                else{
                    tingkat = "XIII";
                }
                String jurusan = rs.getString("nama_jurusan");
                String jenkel = rs.getString("jenkel");
                Date tgl_lahir = rs.getDate("tgl_lahir");
                String alamat = rs.getString("alamat");
                Calendar now = Calendar.getInstance();
                int tahunSkrg = now.get(Calendar.YEAR);
                Calendar birth = Calendar.getInstance();
                birth.setTime(tgl_lahir);
                int tahunLahir = birth.get(Calendar.YEAR);
                
                int usia = tahunSkrg - tahunLahir;
                if (now.get(Calendar.DAY_OF_YEAR)<birth.get(Calendar.DAY_OF_YEAR)) {
                    usia--;
                }
             
                dtm.addRow(new String[]{no+"",nis,nama,tingkat+"-"+namaKelas,jurusan,jenkel,tgl_lahir+"",alamat,usia+""});
                no++;
            }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        tbl_siswa.setModel(dtm);
        fieldTotal.setText(""+totalSiswa);
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agenone;
    private javax.swing.JRadioButton asc;
    private javax.swing.JRadioButton cewe;
    private javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdHapus1;
    private javax.swing.JButton cmdHapus2;
    private javax.swing.JButton cmdHapus3;
    private javax.swing.JButton cmdRefresh;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JRadioButton cowo;
    private javax.swing.JRadioButton desc;
    private javax.swing.JLabel fieldTotal;
    private javax.swing.ButtonGroup filterJK;
    private javax.swing.ButtonGroup filterUsia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jksemua;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTable tbl_siswa;
    // End of variables declaration//GEN-END:variables
}