package koneksidbversipbolegal;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ManageData extends javax.swing.JDialog {

    /**
     * Creates new form ManageData
     */
    Connection koneksi;
    String action; 
    public ManageData(java.awt.Frame parent, boolean modal, String act, String nis) throws SQLException, ParseException {
        super(parent, modal);
        initComponents();
        koneksi = SQLiteConnection.connect();
        
        Statement stm = koneksi.createStatement();
        String que2 = "SELECT * FROM t_kelas GROUP BY id_kelas";
        ResultSet rs2 = stm.executeQuery(que2);
            while(rs2.next()){
                String id_kelas = rs2.getString("nama_kelas");
                cmbKelas.addItem(id_kelas);
            }
                
        String que3 = "SELECT * FROM t_jurusan GROUP BY id_jurusan";
        ResultSet rs3 = stm.executeQuery(que3);
            while(rs3.next()){
                String id_jurusan = rs3.getString("nama_jurusan");
                cmbJurusan.addItem(id_jurusan);
            }
            
        
        action = act;
        if (action.equals("Edit")) {
           lblRenameAble.setText("Edit Data");
           txtNIS.setEnabled(false);
           showData(nis);
       }else{
            lblRenameAble.setText("Tambah Data");
        }
        
    }

    ManageData(DataSiswa aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJK = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbKelas = new javax.swing.JComboBox<>();
        cmbJurusan = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        lblRenameAble = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        txtAlamat = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        txtBulan = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel4.setText("Kelas");

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel5.setText("Jurusan");

        txtNIS.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        txtNama.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        cmbKelas.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[ PILIH KELAS ]" }));
        cmbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelasActionPerformed(evt);
            }
        });

        cmbJurusan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[ PILIH JURUSAN ]" }));

        btnSimpan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        lblRenameAble.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel8.setText("Alamat");

        rbL.setBackground(new java.awt.Color(204, 255, 204));
        rbJK.add(rbL);
        rbL.setText("L");
        rbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLActionPerformed(evt);
            }
        });

        rbP.setBackground(new java.awt.Color(204, 255, 204));
        rbJK.add(rbP);
        rbP.setText("P");

        txtAlamat.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        txtTahun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTahun.setText("Tahun");
        txtTahun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTahunMouseClicked(evt);
            }
        });
        txtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunActionPerformed(evt);
            }
        });

        txtBulan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBulan.setText("Bulan");
        txtBulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBulanMouseClicked(evt);
            }
        });
        txtBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBulanActionPerformed(evt);
            }
        });

        txtTanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTanggal.setText("Tanggal");
        txtTanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTanggalMouseClicked(evt);
            }
        });
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRenameAble, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(46, 46, 46))
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNIS)
                                .addComponent(txtNama)
                                .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbJurusan, 0, 151, Short.MAX_VALUE)
                                .addComponent(btnSimpan)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbL)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbP))
                                .addComponent(txtAlamat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRenameAble, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbL)
                    .addComponent(rbP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(jButton1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(423, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKelasActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (action.equals("Edit")) {
            try {
                editData();
            } catch (ParseException ex) {
                Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
            }
            String edit = "Edit Data";
            lblRenameAble.setText("" + edit);
        }
        else {
            try {
                tambahData();
            } catch (ParseException ex) {
                Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        DataSiswa main = null;
        try {
            main = new DataSiswa();
        } catch (SQLException ex) {
            Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
        }
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLActionPerformed

    private void txtBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBulanActionPerformed
        txtBulan.setText("");
    }//GEN-LAST:event_txtBulanActionPerformed

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunActionPerformed
        txtTahun.setText("");
    }//GEN-LAST:event_txtTahunActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        txtTanggal.setText("");
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtTahunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTahunMouseClicked
        txtTahun.setText("");
    }//GEN-LAST:event_txtTahunMouseClicked

    private void txtBulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBulanMouseClicked
        txtBulan.setText("");
    }//GEN-LAST:event_txtBulanMouseClicked

    private void txtTanggalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTanggalMouseClicked
        txtTanggal.setText("");
    }//GEN-LAST:event_txtTanggalMouseClicked
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }
    public void tambahData() throws ParseException{
        String nis = txtNIS.getText();
        String nama = txtNama.getText();
        String tahun = txtTahun.getText();
        String bulan = txtBulan.getText();
        String tanggal = txtTanggal.getText();
        String alamat = txtAlamat.getText();
        Icon jenkel = rbL.getSelectedIcon();
        String namakelas = cmbKelas.getSelectedItem().toString();
        String id_kelas = "";
        //if id  = 
        if (namakelas.equals("RPL 1")) {
            id_kelas = "1";
        }
        else if (namakelas.equals("RPL 2")) {
            id_kelas = "2";
        }
        else if (namakelas.equalsIgnoreCase("RPL 3")) {
            id_kelas = "3";
        }
        else if (namakelas.equalsIgnoreCase("TKJ")) {
            id_kelas = "4";
        
        }
        else if (namakelas.equalsIgnoreCase("MM")) {
            id_kelas = "5";
        }
        
        else if (namakelas.equalsIgnoreCase("AV 1")) {
            id_kelas = "" + 6;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 2")) {
            id_kelas = "" + 7;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 3")) {
            id_kelas = "" + 8;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 4")) {
            id_kelas = "" + 9;
        }
        
        else if (namakelas.equalsIgnoreCase("TOI 1")) {
            id_kelas = "" + 10;
        }
        
        else if (namakelas.equalsIgnoreCase("TOI 2")) {
            id_kelas = "" + 11;
        }
        
        else if (namakelas.equalsIgnoreCase("TITL 1")) {
            id_kelas = "" + 12;
        
        }
        else if (namakelas.equalsIgnoreCase("TITL 2")) {
            id_kelas = "" + 13;
        
        }
        String namajurusan = cmbJurusan.getSelectedItem().toString();
        String id_jurusan = "";
        if (namajurusan.equalsIgnoreCase("rpl")) {
            id_jurusan = "" + 1;
        }
        else if (namajurusan.equalsIgnoreCase("tkj")) {
            id_jurusan = "" + 2;
        }
        else if (namajurusan.equalsIgnoreCase("mm")) {
            id_jurusan = "" + 3;
        }
        else if (namajurusan.equalsIgnoreCase("teav")) {
            id_jurusan = "" + 4;
        }
        else if (namajurusan.equalsIgnoreCase("titl")) {
            id_jurusan = "" + 5;
        }
        else if (namajurusan.equalsIgnoreCase("toi")) {
            id_jurusan = "" + 6;
        }
        String tgl_lahir = tahun+"-"+bulan+"-"+tanggal;
        String jk = "";
        if (rbL.isSelected()) {
            jk = "L"; 
        }
        else if (rbP.isSelected()) {
            jk = "P"; 
        }
        
        Statement stm = null;
        
        try{
            stm = koneksi.createStatement();
            String query = "INSERT INTO t_siswa(nis,nama,id_kelas,id_jurusan,jenkel,tgl_lahir,alamat)" + "VALUES('"+nis+"','"+nama+"','"+id_kelas+"','"+id_jurusan+"','"+jk+"','"+tgl_lahir+"','"+alamat+"')";
            System.out.println(query);
            int berhasil = stm.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null,"Data berhasil dimasukan");
                this.setVisible(false);
                DataSiswa main = new DataSiswa();
                main.setVisible(true);
                stm.close();
            }else{
                JOptionPane.showMessageDialog(null, "Data gagal dimasukan");
            }
            String que2 = "SELECT * FROM t_kelas GROUP BY id_kelas";
            ResultSet rs2 = stm.executeQuery(que2);
                while(rs2.next()){
                    String kelas = rs2.getString("nama_kelas");
                    cmbKelas.addItem(kelas);
                }
                
            String que3 = "SELECT * FROM t_jurusan GROUP BY id_jurusan";
                ResultSet rs3 = stm.executeQuery(que3);
                while(rs3.next()){
                    String jurusan = rs3.getString("nama_jurusan");
                    cmbJurusan.addItem(jurusan);
                }
        }
        catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi database nya");
        }
        finally{
            try {
                stm.close();
            } catch (SQLException ex) {
                Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    public void showData(String nis){
        try{
            Statement stm = koneksi.createStatement();
            String query = "SELECT * FROM t_siswa WHERE nis = '" + nis + "'";
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()){
            txtNIS.setText(rs.getString("nis"));
            txtNama.setText(rs.getString("nama"));
            cmbKelas.setSelectedItem(rs.getString("id_kelas"));
            cmbJurusan.setSelectedItem(rs.getString("id_jurusan"));
            String que2 = "SELECT * FROM t_kelas GROUP BY id_kelas";
            
                ResultSet rs2 = stm.executeQuery(que2);
                while(rs2.next()){
                    String id_kelas = rs2.getString("nama_kelas");
                    cmbKelas.addItem(id_kelas);
                }
                
                String que3 = "SELECT * FROM t_jurusan GROUP BY id_jurusan";
                ResultSet rs3 = stm.executeQuery(que3);
                while(rs3.next()){
                    String id_jurusan = rs3.getString("nama_jurusan");
                    cmbJurusan.addItem(id_jurusan);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public void editData() throws ParseException, SQLException{
        String nis = txtNIS.getText();
        String nama = txtNama.getText();
        String namakelas = cmbKelas.getSelectedItem().toString();
        String id_kelas = "";
        //if id  = 
        if (namakelas.equals("RPL 1")) {
            id_kelas = "1";
        }
        else if (namakelas.equals("RPL 2")) {
            id_kelas = "2";
        }
        else if (namakelas.equalsIgnoreCase("RPL 3")) {
            id_kelas = "3";
        }
        else if (namakelas.equalsIgnoreCase("TKJ")) {
            id_kelas = "4";
        
        }
        else if (namakelas.equalsIgnoreCase("MM")) {
            id_kelas = "5";
        }
        
        else if (namakelas.equalsIgnoreCase("AV 1")) {
            id_kelas = "" + 6;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 2")) {
            id_kelas = "" + 7;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 3")) {
            id_kelas = "" + 8;
        }
        
        else if (namakelas.equalsIgnoreCase("AV 4")) {
            id_kelas = "" + 9;
        }
        
        else if (namakelas.equalsIgnoreCase("TOI 1")) {
            id_kelas = "" + 10;
        }
        
        else if (namakelas.equalsIgnoreCase("TOI 2")) {
            id_kelas = "" + 11;
        }
        
        else if (namakelas.equalsIgnoreCase("TITL 1")) {
            id_kelas = "" + 12;
        
        }
        else if (namakelas.equalsIgnoreCase("TITL 2")) {
            id_kelas = "" + 13;
        
        }
        String namajurusan = cmbJurusan.getSelectedItem().toString();
        String id_jurusan = "";
        if (namajurusan.equalsIgnoreCase("rpl")) {
            id_jurusan = "" + 1;
        }
        else if (namajurusan.equalsIgnoreCase("tkj")) {
            id_jurusan = "" + 2;
        }
        else if (namajurusan.equalsIgnoreCase("mm")) {
            id_jurusan = "" + 3;
        }
        else if (namajurusan.equalsIgnoreCase("teav")) {
            id_jurusan = "" + 4;
        }
        else if (namajurusan.equalsIgnoreCase("titl")) {
            id_jurusan = "" + 5;
        }
        else if (namajurusan.equalsIgnoreCase("toi")) {
            id_jurusan = "" + 6;
        }
        Icon jenkel = rbL.getSelectedIcon();
        String tahun = txtTahun.getText();
        String bulan = txtBulan.getText();
        String tanggal = txtTanggal.getText();
        String tgl_lahir = tahun+"-"+bulan+"-"+tanggal;
        String jk = "";
        if (rbL.isSelected()) {
            jk = "L"; 
        }
        else if (rbP.isSelected()) {
            jk = "P"; 
        }
        String alamat = txtAlamat.getText();
        
        Statement stm = null;
        try{
            stm = koneksi.createStatement();
            String query = "UPDATE t_siswa SET nama = '" + nama + "', id_kelas = '" + id_kelas +"', id_jurusan = '" + id_jurusan +"', jenkel = '" + jk + "', tgl_lahir ='" + tgl_lahir + "', alamat = '" + alamat + "'WHERE nis = '" + nis + "'"; 
            System.out.println(query);
            int berhasil = stm.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                this.setVisible(false);
                DataSiswa main = new DataSiswa();
                main.setVisible(true);
                stm.close();
            }
            else {
                JOptionPane.showMessageDialog(null, "Data gagal diubah");                      
            }
            
            
        }
        catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Query nya");
        }
        finally{
            stm.close();
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRenameAble;
    private javax.swing.ButtonGroup rbJK;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
